### ISSUE TITLE
the combiner should rewrite assets relative to root

### ISSUE THREAD

**Issue by matthewmueller** [makojs/css#6]
could be missing something (it's late), but....

seems to me like duo-pack is doing something pretty funky, it's resolving relative to the entry file path: https://github.com/duojs/pack/blob/8b0eb4ca84341340670eab13222f7acd913cc42a/lib/css/index.js#L87

which doesn't really work if you have a css file, importing from another css file in a different directory that references a font. I think it should resolve all the urls absolute to the root.

so if we have:

**(entry) pages/home/home.css**
```css
@import "../../lib/raleway/index.css";
```

**lib/raleway/index.css**
```css
@font-face {
  font-family: 'Raleway';
  src: url("fonts/Raleway-Light.ttf");
}
```

with the font files in: `lib/raleway/fonts/`:

It should end up being:

```css
@font-face {
  font-family: 'Raleway';
  src: url("/lib/raleway/fonts/Raleway-Light.ttf");
}
```

Here's a bit of code using post-css to make that happen. Since we have all this information about the file, we don't really need it, but it might be a good ref:

https://github.com/lapwinglabs/www-bundle/blob/164f587f382d08cfcd38fd021a4c85f4f1d80241/index.js#L212-L217
